theme: jekyll-theme-cayman
title: JARQL
github:
    repository_name: "JARQL"
    repository_url: "https://github.com/linked-solutions/jarql"
    release_url: "https://github.com/linked-solutions/jarql/releases/latest"
last_update: 2018-10-04
